/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UpstreamsIndexImport } from './routes/upstreams/index'
import { Route as SslIndexImport } from './routes/ssl/index'
import { Route as ServiceIndexImport } from './routes/service/index'
import { Route as SecretIndexImport } from './routes/secret/index'
import { Route as RouteIndexImport } from './routes/route/index'
import { Route as PluginGlobalRulesIndexImport } from './routes/plugin-global-rules/index'
import { Route as ConsumerIndexImport } from './routes/consumer/index'
import { Route as UpstreamsAddImport } from './routes/upstreams/add'
import { Route as RouteAddImport } from './routes/route/add'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UpstreamsIndexRoute = UpstreamsIndexImport.update({
  id: '/upstreams/',
  path: '/upstreams/',
  getParentRoute: () => rootRoute,
} as any)

const SslIndexRoute = SslIndexImport.update({
  id: '/ssl/',
  path: '/ssl/',
  getParentRoute: () => rootRoute,
} as any)

const ServiceIndexRoute = ServiceIndexImport.update({
  id: '/service/',
  path: '/service/',
  getParentRoute: () => rootRoute,
} as any)

const SecretIndexRoute = SecretIndexImport.update({
  id: '/secret/',
  path: '/secret/',
  getParentRoute: () => rootRoute,
} as any)

const RouteIndexRoute = RouteIndexImport.update({
  id: '/route/',
  path: '/route/',
  getParentRoute: () => rootRoute,
} as any)

const PluginGlobalRulesIndexRoute = PluginGlobalRulesIndexImport.update({
  id: '/plugin-global-rules/',
  path: '/plugin-global-rules/',
  getParentRoute: () => rootRoute,
} as any)

const ConsumerIndexRoute = ConsumerIndexImport.update({
  id: '/consumer/',
  path: '/consumer/',
  getParentRoute: () => rootRoute,
} as any)

const UpstreamsAddRoute = UpstreamsAddImport.update({
  id: '/upstreams/add',
  path: '/upstreams/add',
  getParentRoute: () => rootRoute,
} as any)

const RouteAddRoute = RouteAddImport.update({
  id: '/route/add',
  path: '/route/add',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/route/add': {
      id: '/route/add'
      path: '/route/add'
      fullPath: '/route/add'
      preLoaderRoute: typeof RouteAddImport
      parentRoute: typeof rootRoute
    }
    '/upstreams/add': {
      id: '/upstreams/add'
      path: '/upstreams/add'
      fullPath: '/upstreams/add'
      preLoaderRoute: typeof UpstreamsAddImport
      parentRoute: typeof rootRoute
    }
    '/consumer/': {
      id: '/consumer/'
      path: '/consumer'
      fullPath: '/consumer'
      preLoaderRoute: typeof ConsumerIndexImport
      parentRoute: typeof rootRoute
    }
    '/plugin-global-rules/': {
      id: '/plugin-global-rules/'
      path: '/plugin-global-rules'
      fullPath: '/plugin-global-rules'
      preLoaderRoute: typeof PluginGlobalRulesIndexImport
      parentRoute: typeof rootRoute
    }
    '/route/': {
      id: '/route/'
      path: '/route'
      fullPath: '/route'
      preLoaderRoute: typeof RouteIndexImport
      parentRoute: typeof rootRoute
    }
    '/secret/': {
      id: '/secret/'
      path: '/secret'
      fullPath: '/secret'
      preLoaderRoute: typeof SecretIndexImport
      parentRoute: typeof rootRoute
    }
    '/service/': {
      id: '/service/'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceIndexImport
      parentRoute: typeof rootRoute
    }
    '/ssl/': {
      id: '/ssl/'
      path: '/ssl'
      fullPath: '/ssl'
      preLoaderRoute: typeof SslIndexImport
      parentRoute: typeof rootRoute
    }
    '/upstreams/': {
      id: '/upstreams/'
      path: '/upstreams'
      fullPath: '/upstreams'
      preLoaderRoute: typeof UpstreamsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/route/add': typeof RouteAddRoute
  '/upstreams/add': typeof UpstreamsAddRoute
  '/consumer': typeof ConsumerIndexRoute
  '/plugin-global-rules': typeof PluginGlobalRulesIndexRoute
  '/route': typeof RouteIndexRoute
  '/secret': typeof SecretIndexRoute
  '/service': typeof ServiceIndexRoute
  '/ssl': typeof SslIndexRoute
  '/upstreams': typeof UpstreamsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/route/add': typeof RouteAddRoute
  '/upstreams/add': typeof UpstreamsAddRoute
  '/consumer': typeof ConsumerIndexRoute
  '/plugin-global-rules': typeof PluginGlobalRulesIndexRoute
  '/route': typeof RouteIndexRoute
  '/secret': typeof SecretIndexRoute
  '/service': typeof ServiceIndexRoute
  '/ssl': typeof SslIndexRoute
  '/upstreams': typeof UpstreamsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/route/add': typeof RouteAddRoute
  '/upstreams/add': typeof UpstreamsAddRoute
  '/consumer/': typeof ConsumerIndexRoute
  '/plugin-global-rules/': typeof PluginGlobalRulesIndexRoute
  '/route/': typeof RouteIndexRoute
  '/secret/': typeof SecretIndexRoute
  '/service/': typeof ServiceIndexRoute
  '/ssl/': typeof SslIndexRoute
  '/upstreams/': typeof UpstreamsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/route/add'
    | '/upstreams/add'
    | '/consumer'
    | '/plugin-global-rules'
    | '/route'
    | '/secret'
    | '/service'
    | '/ssl'
    | '/upstreams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/route/add'
    | '/upstreams/add'
    | '/consumer'
    | '/plugin-global-rules'
    | '/route'
    | '/secret'
    | '/service'
    | '/ssl'
    | '/upstreams'
  id:
    | '__root__'
    | '/'
    | '/route/add'
    | '/upstreams/add'
    | '/consumer/'
    | '/plugin-global-rules/'
    | '/route/'
    | '/secret/'
    | '/service/'
    | '/ssl/'
    | '/upstreams/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RouteAddRoute: typeof RouteAddRoute
  UpstreamsAddRoute: typeof UpstreamsAddRoute
  ConsumerIndexRoute: typeof ConsumerIndexRoute
  PluginGlobalRulesIndexRoute: typeof PluginGlobalRulesIndexRoute
  RouteIndexRoute: typeof RouteIndexRoute
  SecretIndexRoute: typeof SecretIndexRoute
  ServiceIndexRoute: typeof ServiceIndexRoute
  SslIndexRoute: typeof SslIndexRoute
  UpstreamsIndexRoute: typeof UpstreamsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RouteAddRoute: RouteAddRoute,
  UpstreamsAddRoute: UpstreamsAddRoute,
  ConsumerIndexRoute: ConsumerIndexRoute,
  PluginGlobalRulesIndexRoute: PluginGlobalRulesIndexRoute,
  RouteIndexRoute: RouteIndexRoute,
  SecretIndexRoute: SecretIndexRoute,
  ServiceIndexRoute: ServiceIndexRoute,
  SslIndexRoute: SslIndexRoute,
  UpstreamsIndexRoute: UpstreamsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/route/add",
        "/upstreams/add",
        "/consumer/",
        "/plugin-global-rules/",
        "/route/",
        "/secret/",
        "/service/",
        "/ssl/",
        "/upstreams/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/route/add": {
      "filePath": "route/add.tsx"
    },
    "/upstreams/add": {
      "filePath": "upstreams/add.tsx"
    },
    "/consumer/": {
      "filePath": "consumer/index.tsx"
    },
    "/plugin-global-rules/": {
      "filePath": "plugin-global-rules/index.tsx"
    },
    "/route/": {
      "filePath": "route/index.tsx"
    },
    "/secret/": {
      "filePath": "secret/index.tsx"
    },
    "/service/": {
      "filePath": "service/index.tsx"
    },
    "/ssl/": {
      "filePath": "ssl/index.tsx"
    },
    "/upstreams/": {
      "filePath": "upstreams/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
