name: Deploy API to Azure

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      etcd:
        image: bitnami/etcd:3.3.13-r80
        ports:
          - 2379:2379
          - 2380:2380
        env:
          ALLOW_NONE_AUTHENTICATION: yes

    steps:
      - uses: actions/checkout@v2

      - name: license check
        run: |
          make license-check

      - name: get lua lib
        run: |
          wget https://github.com/api7/dag-to-lua/archive/v1.1.tar.gz
          sudo mkdir -p /go/manager-api/dag-to-lua/
          tar -zxvf v1.1.tar.gz
          sudo mv ./dag-to-lua-1.1/lib/* /go/manager-api/dag-to-lua/

      - name: install runtime
        run: |
          sudo apt-get update
          sudo apt-get install lua5.1
          sudo add-apt-repository ppa:longsleep/golang-backports
          sudo apt update
          export GO111MOUDULE=on
          sudo apt install golang-1.14-go

      - name: generate json schema
        working-directory: ./api
        run: |
          wget https://github.com/apache/apisix/archive/master.zip
          mkdir -p ./build-tools/apisix/
          unzip master.zip
          sudo mv ./apisix-master/apisix/* ./build-tools/apisix/
          rm -rf ./apisix-master
          cd ./build-tools/ && lua schema-sync.lua > ../conf/schema.json

      - name: run test
        working-directory: ./api
        run: |
          export APIX_ETCD_ENDPOINTS=127.0.0.1:2379
          go test ./...

      - uses: Azure/docker-login@v1
        with:
          login-server: apisixacr.azurecr.cn
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: build and push docker image
        working-directory: ./api
        run: |
          docker build . -t apisixacr.azurecr.cn/managerapi:${{ github.sha }}
          docker push apisixacr.azurecr.cn/managerapi:${{ github.sha }}
