name: golang-lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - v2.0

jobs:
  golangci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: run lint
        run: make golang-lint
