name: License checker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-license:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Check License Header
        uses: apache/skywalking-eyes/header@f4b890e8d2b717a62f75d3c6d0965cc0754a9c1d
