name: License checker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-license:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Check License Header
        uses: apache/skywalking-eyes/header@e910f72bae86171d727742c25f8a4555b7b83893
