name: License checker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-license:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Check License Header
        uses: apache/skywalking-eyes/header@c72515a64b6445f7b079c9cb517271ff65410948
