name: Cancelling Duplicates
on:
  workflow_run:
    workflows:
      - 'Frontend e2e test'
      - 'Frontend e2e test for plugin'
      - 'Test and Deploy with Docker'
      - 'Test building web in multiple node version'
      - 'Backend E2E Test'
      - 'make build'
    types: ['requested']

jobs:
  cancel-duplicate-workflow-runs:
    name: "Cancel duplicate workflow runs"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: ./.github/actions/cancel-workflow-runs
        name: "Cancel duplicate workflow runs"
        with:
          cancelMode: allDuplicates
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}
          skipEventTypes: '["push", "schedule"]'
